[package]
name = "firmware-nrf52832-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
panic-halt = "0.2"

[[bin]]
name = "firmware-nrf52832-demo"
path = "src/main.rs"
test = false
bench = false
