# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.

name: "nrf52832"
arch: "arm"
flash:
  base: 0x00000000
  size: "512KB"
ram:
  base: 0x20000000
  size: "64KB"
peripherals:
  - id: "FICR"
    type: "strict_ir"
    base_address: 0x10000000
    config:
      path: "../../tests/fixtures/real_world/nrf52832.json"
  - id: "UICR"
    type: "strict_ir"
    base_address: 0x10001000
    config:
      path: "../../tests/fixtures/real_world/nrf52832.json"
  - id: "UART0"
    type: "uart"
    base_address: 0x40002000
    size: "4KB"
    config:
      profile: "nrf52"
  - id: "P0"
    type: "gpio"
    base_address: 0x50000000
    size: "4KB"
  - id: "systick"
    type: "systick"
    base_address: 0xE000E010
