[package]
name = "labwired-ir"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = []
svd = ["dep:svd-parser"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
svd-parser = { version = "0.14", optional = true }
thiserror = "1.0"
