[package]
name = "firmware-armv6m-hello"
version = "0.1.0"
edition = "2021"

[dependencies]
panic-halt = "0.2.0"

[[bin]]
name = "firmware-armv6m-hello"
path = "src/main.rs"
test = false
bench = false
