# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

# Linker configuration for ARM targets is handled in build.rs
# of respective crates to avoid global interference.

[build]
target = "thumbv7m-none-eabi"

[target.thumbv7m-none-eabi]
rustflags = []
