[package]
name = "labwired-wasm"
version = "0.12.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.92"
labwired-core = { path = "../core" }
labwired-config = { path = "../config" }
labwired-loader = { path = "../loader" }
cortex-m = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
labwired-gdbstub = { path = "../gdbstub" }
gdbstub = "0.7"
gdbstub_arch = "0.3"
