[package]
name = "firmware-stm32f103-blinky"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"

[[bin]]
name = "firmware-stm32f103-blinky"
test = false
bench = false
