[package]
name = "firmware-rv32i-hello"
version = "0.1.0"
edition = "2021"

[dependencies]
panic-halt = "0.2.0"
riscv-rt = "0.12.0"

[[bin]]
name = "firmware-rv32i-hello"
path = "src/main.rs"
test = false
bench = false
